[package]
name = "dpi_gui"
version = "26.7.9"
description = "DPI Bypass GUI"
authors = ["Sankyuubigan"]
edition = "2021"

[build-dependencies]
tauri-build = { version = "2.0.0", features = [] }

[dependencies]
tauri = { version = "2.0.0", features = [] }
tauri-plugin-shell = "2.0.0"
tauri-plugin-updater = { version = "2", default-features = false, features = ["native-tls", "zip"] }
tauri-plugin-process = "2"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
reqwest = { version = "0.12", features = ["blocking"] }
headless_chrome = { version = "1.0", features = ["fetch"] }
sysinfo = "0.32"
dirs = "5.0"
shlex = "1.3"
url = "2.5"
trust-dns-resolver = "0.23"
windows-sys = { version = "0.52", features = ["Win32_UI_WindowsAndMessaging", "Win32_Foundation", "Win32_System_Threading"] }
