# -*- coding: utf-8 -*-
# Плейсхолдеры для форматирования:
# {LISTS_DIR} - путь к папке 'lists'
# {BIN_DIR} - путь к папке 'bin'
# {GAME_FILTER} - порты для игрового фильтра ("1024-65535" или "0")
PROFILES = [
    # Профили из репозитория Flowseal/zapret-discord-youtube v1.8.5
    {
        "name": "1.8.5 - General",
        "required_lists": ["list-general"],
        "args": "--wf-tcp=80,443,{GAME_FILTER} --wf-udp=443,50000-50100,{GAME_FILTER} --filter-udp=443 --hostlist=\"{LISTS_DIR}\\list-general.txt\" --dpi-desync=fake --dpi-desync-repeats=6 --dpi-desync-fake-quic=\"{BIN_DIR}\\quic_initial_www_google_com.bin\" --new --filter-udp=50000-50100 --filter-l7=discord,stun --dpi-desync=fake --dpi-desync-repeats=6 --new --filter-tcp=80 --hostlist=\"{LISTS_DIR}\\list-general.txt\" --dpi-desync=fake,split2 --dpi-desync-autottl=2 --dpi-desync-fooling=md5sig --new --filter-tcp=443 --hostlist=\"{LISTS_DIR}\\list-general.txt\" --dpi-desync=fake,multidisorder --dpi-desync-split-pos=midsld --dpi-desync-repeats=8 --dpi-desync-fooling=md5sig,badseq --new --filter-udp=443 --ipset=\"{LISTS_DIR}\\ipset-all.txt\" --dpi-desync=fake --dpi-desync-repeats=6 --dpi-desync-fake-quic=\"{BIN_DIR}\\quic_initial_www_google_com.bin\" --new --filter-tcp=80 --ipset=\"{LISTS_DIR}\\ipset-all.txt\" --dpi-desync=fake,split2 --dpi-desync-autottl=2 --dpi-desync-fooling=md5sig --new --filter-tcp=443,{GAME_FILTER} --ipset=\"{LISTS_DIR}\\ipset-all.txt\" --dpi-desync=fake,multidisorder --dpi-desync-split-pos=midsld --dpi-desync-repeats=6 --dpi-desync-fooling=md5sig,badseq --new --filter-udp={GAME_FILTER} --ipset=\"{LISTS_DIR}\\ipset-all.txt\" --dpi-desync=fake --dpi-desync-autottl=2 --dpi-desync-repeats=10 --dpi-desync-any-protocol=1 --dpi-desync-fake-unknown-udp=\"{BIN_DIR}\\quic_initial_www_google_com.bin\" --dpi-desync-cutoff=n2"
    },
    {
        "name": "1.8.5 - General (ALT)",
        "required_lists": ["list-general"],
        "args": "--wf-tcp=80,443,{GAME_FILTER} --wf-udp=443,50000-50100,{GAME_FILTER} --filter-udp=443 --hostlist=\"{LISTS_DIR}\\list-general.txt\" --dpi-desync=fake --dpi-desync-repeats=6 --dpi-desync-fake-quic=\"{BIN_DIR}\\quic_initial_www_google_com.bin\" --new --filter-udp=50000-50100 --filter-l7=discord,stun --dpi-desync=fake --dpi-desync-repeats=6 --new --filter-tcp=80 --hostlist=\"{LISTS_DIR}\\list-general.txt\" --dpi-desync=fake,split2 --dpi-desync-autottl=2 --dpi-desync-fooling=md5sig --new --filter-tcp=443 --hostlist=\"{LISTS_DIR}\\list-general.txt\" --dpi-desync=fake,split --dpi-desync-autottl=5 --dpi-desync-repeats=6 --dpi-desync-fooling=badseq --dpi-desync-fake-tls=\"{BIN_DIR}\\tls_clienthello_www_google_com.bin\" --new --filter-udp=443 --ipset=\"{LISTS_DIR}\\ipset-all.txt\" --dpi-desync=fake --dpi-desync-repeats=6 --dpi-desync-fake-quic=\"{BIN_DIR}\\quic_initial_www_google_com.bin\" --new --filter-tcp=80 --ipset=\"{LISTS_DIR}\\ipset-all.txt\" --dpi-desync=fake,split2 --dpi-desync-autottl=2 --dpi-desync-fooling=md5sig --new --filter-tcp=443,{GAME_FILTER} --ipset=\"{LISTS_DIR}\\ipset-all.txt\" --dpi-desync=fake,split --dpi-desync-autottl=5 --dpi-desync-repeats=6 --dpi-desync-fooling=badseq --dpi-desync-fake-tls=\"{BIN_DIR}\\tls_clienthello_www_google_com.bin\" --new --filter-udp={GAME_FILTER} --ipset=\"{LISTS_DIR}\\ipset-all.txt\" --dpi-desync=fake --dpi-desync-autottl=2 --dpi-desync-repeats=12 --dpi-desync-any-protocol=1 --dpi-desync-fake-unknown-udp=\"{BIN_DIR}\\quic_initial_www_google_com.bin\" --dpi-desync-cutoff=n3"
    },
    {
        "name": "1.8.5 - General (ALT2)",
        "required_lists": ["list-general"],
        "args": "--wf-tcp=80,443,2053,2083,2087,2096,8443,{GAME_FILTER} --wf-udp=443,19294-19344,50000-50100,{GAME_FILTER} --filter-udp=443 --hostlist=\"{LISTS_DIR}\\list-general.txt\" --dpi-desync=fake --dpi-desync-repeats=6 --dpi-desync-fake-quic=\"{BIN_DIR}\\quic_initial_www_google_com.bin\" --new --filter-udp=19294-19344,50000-50100 --filter-l7=discord,stun --dpi-desync=fake --dpi-desync-repeats=6 --new --filter-tcp=80 --hostlist=\"{LISTS_DIR}\\list-general.txt\" --dpi-desync=fake,multisplit --dpi-desync-autottl=2 --dpi-desync-fooling=md5sig --new --filter-tcp=2053,2083,2087,2096,8443 --hostlist-domains=discord.media --dpi-desync=multisplit --dpi-desync-split-seqovl=652 --dpi-desync-split-pos=2 --dpi-desync-split-seqovl-pattern=\"{BIN_DIR}\\tls_clienthello_www_google_com.bin\" --new --filter-tcp=443 --hostlist=\"{LISTS_DIR}\\list-general.txt\" --dpi-desync=multisplit --dpi-desync-split-seqovl=652 --dpi-desync-split-pos=2 --dpi-desync-split-seqovl-pattern=\"{BIN_DIR}\\tls_clienthello_www_google_com.bin\" --new --filter-udp=443 --ipset=\"{LISTS_DIR}\\ipset-all.txt\" --dpi-desync=fake --dpi-desync-repeats=6 --dpi-desync-fake-quic=\"{BIN_DIR}\\quic_initial_www_google_com.bin\" --new --filter-tcp=80 --ipset=\"{LISTS_DIR}\\ipset-all.txt\" --dpi-desync=fake,multisplit --dpi-desync-autottl=2 --dpi-desync-fooling=md5sig --new --filter-tcp=443,{GAME_FILTER} --ipset=\"{LISTS_DIR}\\ipset-all.txt\" --dpi-desync=multisplit --dpi-desync-split-seqovl=652 --dpi-desync-split-pos=2 --dpi-desync-split-seqovl-pattern=\"{BIN_DIR}\\tls_clienthello_www_google_com.bin\" --new --filter-udp={GAME_FILTER} --ipset=\"{LISTS_DIR}\\ipset-all.txt\" --dpi-desync=fake --dpi-desync-autottl=2 --dpi-desync-repeats=12 --dpi-desync-any-protocol=1 --dpi-desync-fake-unknown-udp=\"{BIN_DIR}\\quic_initial_www_google_com.bin\" --dpi-desync-cutoff=n2"
    },
    {
        "name": "1.8.5 - General (ALT3)",
        "required_lists": ["list-general"],
        "args": "--wf-tcp=80,443,2053,2083,2087,2096,8443,{GAME_FILTER} --wf-udp=443,19294-19344,50000-50100,{GAME_FILTER} --filter-udp=443 --hostlist=\"{LISTS_DIR}\\list-general.txt\" --dpi-desync=fake --dpi-desync-repeats=6 --dpi-desync-fake-quic=\"{BIN_DIR}\\quic_initial_www_google_com.bin\" --new --filter-udp=19294-19344,50000-50100 --filter-l7=discord,stun --dpi-desync=fake --dpi-desync-repeats=6 --new --filter-tcp=80 --hostlist=\"{LISTS_DIR}\\list-general.txt\" --dpi-desync=fake,split2 --dpi-desync-autottl=2 --dpi-desync-fooling=md5sig --new --filter-tcp=2053,2083,2087,2096,8443 --hostlist-domains=discord.media --dpi-desync=fakedsplit --dpi-desync-split-pos=1 --dpi-desync-autottl --dpi-desync-fooling=badseq --dpi-desync-repeats=8 --new --filter-tcp=443 --hostlist=\"{LISTS_DIR}\\list-general.txt\" --dpi-desync=fakedsplit --dpi-desync-split-pos=1 --dpi-desync-autottl --dpi-desync-fooling=badseq --dpi-desync-repeats=8 --new --filter-udp=443 --ipset=\"{LISTS_DIR}\\ipset-all.txt\" --dpi-desync=fake --dpi-desync-repeats=6 --dpi-desync-fake-quic=\"{BIN_DIR}\\quic_initial_www_google_com.bin\" --new --filter-tcp=80 --ipset=\"{LISTS_DIR}\\ipset-all.txt\" --dpi-desync=fake,split2 --dpi-desync-autottl=2 --dpi-desync-fooling=md5sig --new --filter-tcp=443,{GAME_FILTER} --ipset=\"{LISTS_DIR}\\ipset-all.txt\" --dpi-desync=fakedsplit --dpi-desync-split-pos=1 --dpi-desync-autottl --dpi-desync-fooling=badseq --dpi-desync-repeats=8 --new --filter-udp={GAME_FILTER} --ipset=\"{LISTS_DIR}\\ipset-all.txt\" --dpi-desync=fake --dpi-desync-autottl=2 --dpi-desync-repeats=10 --dpi-desync-any-protocol=1 --dpi-desync-fake-unknown-udp=\"{BIN_DIR}\\quic_initial_www_google_com.bin\" --dpi-desync-cutoff=n2"
    },
    {
        "name": "1.8.5 - General (ALT7)",
        "required_lists": ["list-general"],
        "args": "--wf-tcp=80,443,2053,2083,2087,2096,8443,{GAME_FILTER} --wf-udp=443,19294-19344,50000-50100,{GAME_FILTER} --filter-udp=443 --hostlist=\"{LISTS_DIR}\\list-general.txt\" --dpi-desync=fake --dpi-desync-repeats=6 --dpi-desync-fake-quic=\"{BIN_DIR}\\quic_initial_www_google_com.bin\" --new --filter-udp=19294-19344,50000-50100 --filter-l7=discord,stun --dpi-desync=fake --dpi-desync-repeats=6 --new --filter-tcp=80 --hostlist=\"{LISTS_DIR}\\list-general.txt\" --dpi-desync=fake,multisplit --dpi-desync-autottl=2 --dpi-desync-fooling=md5sig --new --filter-tcp=2053,2083,2087,2096,8443 --hostlist-domains=discord.media --dpi-desync=multisplit --dpi-desync-split-pos=2,sniext+1 --dpi-desync-split-seqovl=679 --dpi-desync-split-seqovl-pattern=\"{BIN_DIR}\\tls_clienthello_www_google_com.bin\" --new --filter-tcp=443 --hostlist=\"{LISTS_DIR}\\list-general.txt\" --dpi-desync=multisplit --dpi-desync-split-pos=2,sniext+1 --dpi-desync-split-seqovl=679 --dpi-desync-split-seqovl-pattern=\"{BIN_DIR}\\tls_clienthello_www_google_com.bin\" --new --filter-udp=443 --ipset=\"{LISTS_DIR}\\ipset-all.txt\" --dpi-desync=fake --dpi-desync-repeats=6 --dpi-desync-fake-quic=\"{BIN_DIR}\\quic_initial_www_google_com.bin\" --new --filter-tcp=80 --ipset=\"{LISTS_DIR}\\ipset-all.txt\" --dpi-desync=fake,multisplit --dpi-desync-autottl=2 --dpi-desync-fooling=md5sig --new --filter-tcp=443,{GAME_FILTER} --ipset=\"{LISTS_DIR}\\ipset-all.txt\" --dpi-desync=syndata --new --filter-udp={GAME_FILTER} --ipset=\"{LISTS_DIR}\\ipset-all.txt\" --dpi-desync=fake --dpi-desync-autottl=2 --dpi-desync-repeats=12 --dpi-desync-any-protocol=1 --dpi-desync-fake-unknown-udp=\"{BIN_DIR}\\quic_initial_www_google_com.bin\" --dpi-desync-cutoff=n2"
    },
    {
        "name": "1.8.5 - General (ALT8)",
        "required_lists": ["list-general"],
        "args": "--wf-tcp=80,443,2053,2083,2087,2096,8443,{GAME_FILTER} --wf-udp=443,19294-19344,50000-50100,{GAME_FILTER} --filter-udp=443 --hostlist=\"{LISTS_DIR}\\list-general.txt\" --dpi-desync=fake --dpi-desync-repeats=6 --dpi-desync-fake-quic=\"{BIN_DIR}\\quic_initial_www_google_com.bin\" --new --filter-udp=19294-19344,50000-50100 --filter-l7=discord,stun --dpi-desync=fake --dpi-desync-repeats=6 --new --filter-tcp=80 --hostlist=\"{LISTS_DIR}\\list-general.txt\" --dpi-desync=fake,split2 --dpi-desync-autottl=2 --dpi-desync-fooling=badseq --dpi-desync-badseq-increment=2 --new --filter-tcp=2053,2083,2087,2096,8443 --hostlist-domains=discord.media --dpi-desync=fake --dpi-desync-fake-tls-mod=none --dpi-desync-repeats=6 --dpi-desync-fooling=badseq --dpi-desync-badseq-increment=2 --new --filter-tcp=443 --hostlist=\"{LISTS_DIR}\\list-general.txt\" --dpi-desync=fake --dpi-desync-fake-tls-mod=none --dpi-desync-repeats=6 --dpi-desync-fooling=badseq --dpi-desync-badseq-increment=2 --new --filter-udp=443 --ipset=\"{LISTS_DIR}\\ipset-all.txt\" --dpi-desync=fake --dpi-desync-repeats=6 --dpi-desync-fake-quic=\"{BIN_DIR}\\quic_initial_www_google_com.bin\" --new --filter-tcp=80 --ipset=\"{LISTS_DIR}\\ipset-all.txt\" --dpi-desync=fake,split2 --dpi-desync-autottl=2 --dpi-desync-fooling=badseq --dpi-desync-badseq-increment=2 --new --filter-tcp=443,{GAME_FILTER} --ipset=\"{LISTS_DIR}\\ipset-all.txt\" --dpi-desync=syndata --new --filter-udp={GAME_FILTER} --ipset=\"{LISTS_DIR}\\ipset-all.txt\" --dpi-desync=fake --dpi-desync-autottl=2 --dpi-desync-repeats=12 --dpi-desync-any-protocol=1 --dpi-desync-fake-unknown-udp=\"{BIN_DIR}\\quic_initial_www_google_com.bin\" --dpi-desync-cutoff=n2"
    },
    {
        "name": "1.8.5 - General (FAKE TLS)",
        "required_lists": ["list-general"],
        "args": "--wf-tcp=80,443,{GAME_FILTER} --wf-udp=443,50000-50100,{GAME_FILTER} --filter-udp=443 --hostlist=\"{LISTS_DIR}\\list-general.txt\" --dpi-desync=fake --dpi-desync-repeats=8 --dpi-desync-fake-quic=\"{BIN_DIR}\\quic_initial_www_google_com.bin\" --new --filter-udp=50000-50100 --filter-l7=discord,stun --dpi-desync=fake --dpi-desync-repeats=6 --new --filter-tcp=80 --hostlist=\"{LISTS_DIR}\\list-general.txt\" --dpi-desync=fake,split2 --dpi-desync-autottl=3 --dpi-desync-fooling=md5sig --new --filter-tcp=443 --hostlist=\"{LISTS_DIR}\\list-general.txt\" --dpi-desync=fake --dpi-desync-ttl=4 --dpi-desync-fake-tls-mod=rnd,rndsni,padencap --new --filter-udp=443 --ipset=\"{LISTS_DIR}\\ipset-all.txt\" --dpi-desync=fake --dpi-desync-repeats=8 --dpi-desync-fake-quic=\"{BIN_DIR}\\quic_initial_www_google_com.bin\" --new --filter-tcp=80 --ipset=\"{LISTS_DIR}\\ipset-all.txt\" --dpi-desync=fake,split2 --dpi-desync-autottl=3 --dpi-desync-fooling=md5sig --new --filter-tcp=443,{GAME_FILTER} --ipset=\"{LISTS_DIR}\\ipset-all.txt\" --dpi-desync=fake --dpi-desync-ttl=4 --dpi-desync-fake-tls-mod=rnd,rndsni,padencap --new --filter-udp={GAME_FILTER} --ipset=\"{LISTS_DIR}\\ipset-all.txt\" --dpi-desync=fake --dpi-desync-autottl=2 --dpi-desync-repeats=12 --dpi-desync-any-protocol=1 --dpi-desync-fake-unknown-udp=\"{BIN_DIR}\\quic_initial_www_google_com.bin\" --dpi-desync-cutoff=n3"
    },
    {
        "name": "1.8.5 - General (МГТС)",
        "required_lists": ["list-general"],
        "args": "--wf-tcp=80,443,{GAME_FILTER} --wf-udp=443,50000-50100,{GAME_FILTER} --filter-udp=443 --hostlist=\"{LISTS_DIR}\\list-general.txt\" --dpi-desync=fake --dpi-desync-repeats=6 --dpi-desync-fake-quic=\"{BIN_DIR}\\quic_initial_www_google_com.bin\" --new --filter-udp=50000-50100 --filter-l7=discord,stun --dpi-desync=fake --dpi-desync-repeats=6 --new --filter-tcp=80 --hostlist=\"{LISTS_DIR}\\list-general.txt\" --dpi-desync=fake,split2 --dpi-desync-autottl=2 --dpi-desync-fooling=md5sig --new --filter-tcp=443 --hostlist=\"{LISTS_DIR}\\list-general.txt\" --dpi-desync=fake --dpi-desync-autottl=2 --dpi-desync-repeats=6 --dpi-desync-fooling=badseq --dpi-desync-fake-tls=\"{BIN_DIR}\\tls_clienthello_www_google_com.bin\" --new --filter-udp=443 --ipset=\"{LISTS_DIR}\\ipset-all.txt\" --dpi-desync=fake --dpi-desync-repeats=6 --dpi-desync-fake-quic=\"{BIN_DIR}\\quic_initial_www_google_com.bin\" --new --filter-tcp=80 --ipset=\"{LISTS_DIR}\\ipset-all.txt\" --dpi-desync=fake,split2 --dpi-desync-autottl=2 --dpi-desync-fooling=md5sig --new --filter-tcp=443,{GAME_FILTER} --ipset=\"{LISTS_DIR}\\ipset-all.txt\" --dpi-desync=fake --dpi-desync-autottl=2 --dpi-desync-repeats=6 --dpi-desync-fooling=badseq --dpi-desync-fake-tls=\"{BIN_DIR}\\tls_clienthello_www_google_com.bin\" --new --filter-udp={GAME_FILTER} --ipset=\"{LISTS_DIR}\\ipset-all.txt\" --dpi-desync=fake --dpi-desync-autottl=2 --dpi-desync-repeats=10 --dpi-desync-any-protocol=1 --dpi-desync-fake-unknown-udp=\"{BIN_DIR}\\quic_initial_www_google_com.bin\" --dpi-desync-cutoff=n2"
    },
    {
        "name": "1.8.5 - General (AUTO)",
        "required_lists": ["list-general"],
        "args": "--wf-tcp=80,443,{GAME_FILTER} --wf-udp=443,50000-50100,{GAME_FILTER} --filter-udp=443 --hostlist=\"{LISTS_DIR}\\list-general.txt\" --dpi-desync=fake --dpi-desync-repeats=6 --dpi-desync-fake-quic=\"{BIN_DIR}\\quic_initial_www_google_com.bin\" --new --filter-udp=50000-50100 --filter-l7=discord,stun --dpi-desync=fake --dpi-desync-repeats=6 --new --filter-tcp=80 --hostlist=\"{LISTS_DIR}\\list-general.txt\" --dpi-desync=fake,split2 --dpi-desync-autottl=2 --dpi-desync-fooling=md5sig --new --filter-tcp=443 --hostlist=\"{LISTS_DIR}\\list-general.txt\" --dpi-desync=fake --dpi-desync-autottl=2 --dpi-desync-repeats=6 --dpi-desync-fooling=badseq --dpi-desync-fake-tls=\"{BIN_DIR}\\tls_clienthello_www_google_com.bin\" --new --filter-udp=443 --ipset=\"{LISTS_DIR}\\ipset-all.txt\" --dpi-desync=fake --dpi-desync-repeats=6 --dpi-desync-fake-quic=\"{BIN_DIR}\\quic_initial_www_google_com.bin\" --new --filter-tcp=80 --ipset=\"{LISTS_DIR}\\ipset-all.txt\" --dpi-desync=fake,split2 --dpi-desync-autottl=2 --dpi-desync-fooling=md5sig --new --filter-tcp=443,{GAME_FILTER} --ipset=\"{LISTS_DIR}\\ipset-all.txt\" --dpi-desync=fake --dpi-desync-autottl=2 --dpi-desync-repeats=6 --dpi-desync-fooling=badseq --dpi-desync-fake-tls=\"{BIN_DIR}\\tls_clienthello_www_google_com.bin\" --new --filter-udp={GAME_FILTER} --ipset=\"{LISTS_DIR}\\ipset-all.txt\" --dpi-desync=fake --dpi-desync-autottl=2 --dpi-desync-repeats=10 --dpi-desync-any-protocol=1 --dpi-desync-fake-unknown-udp=\"{BIN_DIR}\\quic_initial_www_google_com.bin\" --dpi-desync-cutoff=n2"
    }
]