# -*- coding: utf-8 -*-

# Плейсхолдеры для форматирования:
# {LISTS_DIR} - путь к папке 'lists'
# {BIN_DIR} - путь к папке 'bin'
# {GAME_FILTER} - порты для игрового фильтра ("1024-65535" или "0")

PROFILES = [
    {
        "name": "Игровой (Макс. совместимость)",
        "args": "--wf-tcp=80,443 --wf-udp=443,50000-50100 "
                "--filter-udp=443 --hostlist=\"{LISTS_DIR}\\list-for-games.txt\" --dpi-desync=fake --dpi-desync-repeats=6 --dpi-desync-fake-quic=\"{BIN_DIR}\\quic_initial_www_google_com.bin\" --new "
                "--filter-udp=50000-50100 --filter-l7=discord,stun --dpi-desync=fake --dpi-desync-repeats=6 --new "
                "--filter-tcp=80 --hostlist=\"{LISTS_DIR}\\list-for-games.txt\" --dpi-desync=fake,split2 --dpi-desync-autottl=2 --dpi-desync-fooling=md5sig --new "
                "--filter-tcp=443 --hostlist=\"{LISTS_DIR}\\list-for-games.txt\" --dpi-desync=fake,split --dpi-desync-autottl=5 --dpi-desync-repeats=6 --dpi-desync-fooling=badseq --dpi-desync-fake-tls=\"{BIN_DIR}\\tls_clienthello_www_google_com.bin\""
    },
    {
        "name": "General (Основной)",
        "args": "--wf-tcp=80,443,{GAME_FILTER} --wf-udp=443,50000-50100,{GAME_FILTER} --filter-udp=443 --hostlist=\"{LISTS_DIR}\\list-general.txt\" --dpi-desync=fake --dpi-desync-repeats=6 --dpi-desync-fake-quic=\"{BIN_DIR}\\quic_initial_www_google_com.bin\" --new --filter-udp=50000-50100 --filter-l7=discord,stun --dpi-desync=fake --dpi-desync-repeats=6 --new --filter-tcp=80 --hostlist=\"{LISTS_DIR}\\list-general.txt\" --dpi-desync=fake,split2 --dpi-desync-autottl=2 --dpi-desync-fooling=md5sig --new --filter-tcp=443 --hostlist=\"{LISTS_DIR}\\list-general.txt\" --dpi-desync=fake,multidisorder --dpi-desync-split-pos=midsld --dpi-desync-repeats=8 --dpi-desync-fooling=md5sig,badseq --new --filter-udp=443 --ipset=\"{LISTS_DIR}\\ipset-all.txt\" --dpi-desync=fake --dpi-desync-repeats=6 --dpi-desync-fake-quic=\"{BIN_DIR}\\quic_initial_www_google_com.bin\" --new --filter-tcp=80 --ipset=\"{LISTS_DIR}\\ipset-all.txt\" --dpi-desync=fake,split2 --dpi-desync-autottl=2 --dpi-desync-fooling=md5sig --new --filter-tcp=443,{GAME_FILTER} --ipset=\"{LISTS_DIR}\\ipset-all.txt\" --dpi-desync=fake,multidisorder --dpi-desync-split-pos=midsld --dpi-desync-repeats=6 --dpi-desync-fooling=md5sig,badseq --new --filter-udp={GAME_FILTER} --ipset=\"{LISTS_DIR}\\ipset-all.txt\" --dpi-desync=fake --dpi-desync-autottl=2 --dpi-desync-repeats=10 --dpi-desync-any-protocol=1 --dpi-desync-fake-unknown-udp=\"{BIN_DIR}\\quic_initial_www_google_com.bin\" --dpi-desync-cutoff=n2"
    },
    {
        "name": "General (ALT)",
        "args": "--wf-tcp=80,443,{GAME_FILTER} --wf-udp=443,50000-50100,{GAME_FILTER} --filter-udp=443 --hostlist=\"{LISTS_DIR}\\list-general.txt\" --dpi-desync=fake --dpi-desync-repeats=6 --dpi-desync-fake-quic=\"{BIN_DIR}\\quic_initial_www_google_com.bin\" --new --filter-udp=50000-50100 --filter-l7=discord,stun --dpi-desync=fake --dpi-desync-repeats=6 --new --filter-tcp=80 --hostlist=\"{LISTS_DIR}\\list-general.txt\" --dpi-desync=fake,split2 --dpi-desync-autottl=2 --dpi-desync-fooling=md5sig --new --filter-tcp=443 --hostlist=\"{LISTS_DIR}\\list-general.txt\" --dpi-desync=fake,split --dpi-desync-autottl=5 --dpi-desync-repeats=6 --dpi-desync-fooling=badseq --dpi-desync-fake-tls=\"{BIN_DIR}\\tls_clienthello_www_google_com.bin\" --new --filter-udp=443 --ipset=\"{LISTS_DIR}\\ipset-all.txt\" --dpi-desync=fake --dpi-desync-repeats=6 --dpi-desync-fake-quic=\"{BIN_DIR}\\quic_initial_www_google_com.bin\" --new --filter-tcp=80 --ipset=\"{LISTS_DIR}\\ipset-all.txt\" --dpi-desync=fake,split2 --dpi-desync-autottl=2 --dpi-desync-fooling=md5sig --new --filter-tcp=443,{GAME_FILTER} --ipset=\"{LISTS_DIR}\\ipset-all.txt\" --dpi-desync=fake,split --dpi-desync-autottl=5 --dpi-desync-repeats=6 --dpi-desync-fooling=badseq --dpi-desync-fake-tls=\"{BIN_DIR}\\tls_clienthello_www_google_com.bin\" --new --filter-udp={GAME_FILTER} --ipset=\"{LISTS_DIR}\\ipset-all.txt\" --dpi-desync=fake --dpi-desync-autottl=2 --dpi-desync-repeats=12 --dpi-desync-any-protocol=1 --dpi-desync-fake-unknown-udp=\"{BIN_DIR}\\quic_initial_www_google_com.bin\" --dpi-desync-cutoff=n3"
    },
    {
        "name": "General (ALT2)",
        "args": "--wf-tcp=80,443,{GAME_FILTER} --wf-udp=443,50000-50100,{GAME_FILTER} --filter-udp=443 --hostlist=\"{LISTS_DIR}\\list-general.txt\" --dpi-desync=fake --dpi-desync-repeats=6 --dpi-desync-fake-quic=\"{BIN_DIR}\\quic_initial_www_google_com.bin\" --new --filter-udp=50000-50100 --filter-l7=discord,stun --dpi-desync=fake --dpi-desync-repeats=6 --new --filter-tcp=80 --hostlist=\"{LISTS_DIR}\\list-general.txt\" --dpi-desync=fake,split2 --dpi-desync-autottl=2 --dpi-desync-fooling=md5sig --new --filter-tcp=443 --hostlist=\"{LISTS_DIR}\\list-general.txt\" --dpi-desync=split2 --dpi-desync-split-seqovl=652 --dpi-desync-split-pos=2 --dpi-desync-split-seqovl-pattern=\"{BIN_DIR}\\tls_clienthello_www_google_com.bin\" --new --filter-udp=443 --ipset=\"{LISTS_DIR}\\ipset-all.txt\" --dpi-desync=fake --dpi-desync-repeats=6 --dpi-desync-fake-quic=\"{BIN_DIR}\\quic_initial_www_google_com.bin\" --new --filter-tcp=80 --ipset=\"{LISTS_DIR}\\ipset-all.txt\" --dpi-desync=fake,split2 --dpi-desync-autottl=2 --dpi-desync-fooling=md5sig --new --filter-tcp=443,{GAME_FILTER} --ipset=\"{LISTS_DIR}\\ipset-all.txt\" --dpi-desync=split2 --dpi-desync-split-seqovl=652 --dpi-desync-split-pos=2 --dpi-desync-split-seqovl-pattern=\"{BIN_DIR}\\tls_clienthello_www_google_com.bin\" --new --filter-udp={GAME_FILTER} --ipset=\"{LISTS_DIR}\\ipset-all.txt\" --dpi-desync=fake --dpi-desync-autottl=2 --dpi-desync-repeats=12 --dpi-desync-any-protocol=1 --dpi-desync-fake-unknown-udp=\"{BIN_DIR}\\quic_initial_www_google_com.bin\" --dpi-desync-cutoff=n2"
    },
    {
        "name": "General (FAKE TLS)",
        "args": "--wf-tcp=80,443,{GAME_FILTER} --wf-udp=443,50000-50100,{GAME_FILTER} --filter-udp=443 --hostlist=\"{LISTS_DIR}\\list-general.txt\" --dpi-desync=fake --dpi-desync-repeats=8 --dpi-desync-fake-quic=\"{BIN_DIR}\\quic_initial_www_google_com.bin\" --new --filter-udp=50000-50100 --filter-l7=discord,stun --dpi-desync=fake --dpi-desync-repeats=6 --new --filter-tcp=80 --hostlist=\"{LISTS_DIR}\\list-general.txt\" --dpi-desync=fake,split2 --dpi-desync-autottl=3 --dpi-desync-fooling=md5sig --new --filter-tcp=443 --hostlist=\"{LISTS_DIR}\\list-general.txt\" --dpi-desync=fake --dpi-desync-ttl=4 --dpi-desync-fake-tls-mod=rnd,rndsni,padencap --new --filter-udp=443 --ipset=\"{LISTS_DIR}\\ipset-all.txt\" --dpi-desync=fake --dpi-desync-repeats=8 --dpi-desync-fake-quic=\"{BIN_DIR}\\quic_initial_www_google_com.bin\" --new --filter-tcp=80 --ipset=\"{LISTS_DIR}\\ipset-all.txt\" --dpi-desync=fake,split2 --dpi-desync-autottl=3 --dpi-desync-fooling=md5sig --new --filter-tcp=443,{GAME_FILTER} --ipset=\"{LISTS_DIR}\\ipset-all.txt\" --dpi-desync=fake --dpi-desync-ttl=4 --dpi-desync-fake-tls-mod=rnd,rndsni,padencap --new --filter-udp={GAME_FILTER} --ipset=\"{LISTS_DIR}\\ipset-all.txt\" --dpi-desync=fake --dpi-desync-autottl=2 --dpi-desync-repeats=12 --dpi-desync-any-protocol=1 --dpi-desync-fake-unknown-udp=\"{BIN_DIR}\\quic_initial_www_google_com.bin\" --dpi-desync-cutoff=n3"
    },
    {
        "name": "General (МГТС)",
        "args": "--wf-tcp=80,443,{GAME_FILTER} --wf-udp=443,50000-50100,{GAME_FILTER} --filter-udp=443 --hostlist=\"{LISTS_DIR}\\list-general.txt\" --dpi-desync=fake --dpi-desync-repeats=6 --dpi-desync-fake-quic=\"{BIN_DIR}\\quic_initial_www_google_com.bin\" --new --filter-udp=50000-50100 --filter-l7=discord,stun --dpi-desync=fake --dpi-desync-repeats=6 --new --filter-tcp=80 --hostlist=\"{LISTS_DIR}\\list-general.txt\" --dpi-desync=fake,split2 --dpi-desync-autottl=2 --dpi-desync-fooling=md5sig --new --filter-tcp=443 --hostlist=\"{LISTS_DIR}\\list-general.txt\" --dpi-desync=fake --dpi-desync-autottl=2 --dpi-desync-repeats=6 --dpi-desync-fooling=badseq --dpi-desync-fake-tls=\"{BIN_DIR}\\tls_clienthello_www_google_com.bin\" --new --filter-udp=443 --ipset=\"{LISTS_DIR}\\ipset-all.txt\" --dpi-desync=fake --dpi-desync-repeats=6 --dpi-desync-fake-quic=\"{BIN_DIR}\\quic_initial_www_google_com.bin\" --new --filter-tcp=80 --ipset=\"{LISTS_DIR}\\ipset-all.txt\" --dpi-desync=fake,split2 --dpi-desync-autottl=2 --dpi-desync-fooling=md5sig --new --filter-tcp=443,{GAME_FILTER} --ipset=\"{LISTS_DIR}\\ipset-all.txt\" --dpi-desync=fake --dpi-desync-autottl=2 --dpi-desync-repeats=6 --dpi-desync-fooling=badseq --dpi-desync-fake-tls=\"{BIN_DIR}\\tls_clienthello_www_google_com.bin\" --new --filter-udp={GAME_FILTER} --ipset=\"{LISTS_DIR}\\ipset-all.txt\" --dpi-desync=fake --dpi-desync-autottl=2 --dpi-desync-repeats=10 --dpi-desync-any-protocol=1 --dpi-desync-fake-unknown-udp=\"{BIN_DIR}\\quic_initial_www_google_com.bin\" --dpi-desync-cutoff=n2"
    }
]